-- Rebuild glint_delivery from Master_Project_Overview.xlsx (MASTER + Old Projects). Backup: _dq_backup_glint_delivery_20260608
delete from glint_delivery;
insert into glint_delivery (sheet_key,client_name,project_name,service_type,region,status,priority,cs_owner,cs_hours,ps_owner,ps_hours,other_contractors,other_hours,ko_date,survey_date,insight_review_date,delivery_end,delivery_start,next_milestone_label,next_milestone_date,notes,follow_up,synced_at) values
('Alex Lee|Alex Lee-Insight review-Q3-2025','Alex Lee','Alex Lee-Insight review-Q3-2025','CS and PS Support','US','In progress','Low','Heidi Muhle',43,'Paul Mastrangelo',65,'Stephanie Noack',3,NULL,NULL,NULL,'Inside review beginning of march','2026-08-01',NULL,NULL,'None- waiting to launch survey beginning of 2026',NULL,now()),
('GoDaddy|GoDaddy-Q3-2025','GoDaddy','GoDaddy-Q3-2025','CS and PS V&S support','US','In progress','High','Heidi Muhle',66,'Paul Mastrangelo',37,'Joanne Wong',3,NULL,NULL,NULL,'End of Feb 2026','2025-07-02','Delivery end 2026-02-15','2026-02-15','Moving to Qualtrics 2nd half of 2026','Meeting with Marco',now()),
('Sage|Sage-2026','Sage','Sage-2026','PS support','UK','In progress','Low','N/A',0,'Kirsty Thompson - Clarke',131,'Avneeta Solanki',4,NULL,NULL,NULL,'2026-12-31','May-2026','Delivery end 2026-12-31','2026-12-31','Purchased 6 insight reviews. 2 have been delivered. 4 remaining to be delivered in 2026. No confirmed dates yet for March 2026 and September 2026 [ulses - this is likely when they will need their insights review completed 4.3 mail Kirsty: Sage Survey is live 5th to the 15th May - they have two presentations so likely these would be delivered W/C 25th May and W/C 1st June but I have asked mel to confirm',NULL,now()),
('Jazz Pharmaceuticals|Jazz-2026','Jazz Pharmaceuticals','Jazz-2026','CS and PS Support','USA/UK','In progress','Medium','Angela Schwingel',120,'Avneeta Solanki',59,'Kirsty Thompson - Clarke',4,NULL,NULL,NULL,'Mid June-26','2026-01-01','Delivery end 2026-06-15','2026-06-15','Angie may need some support with VG platform implementation as its her first one outside of MSFT. Avneeta has not yet delivered these services as a partner and contractor so there is allocated hours for Kirsty to provide her with support. 28-1-2026 Email Avneeta: I''m doing well thank you! Hope you are too. With Jazz, they told us they are running their survey in May so I would imagine delivering the Insights by mid-June. Input Avneet 12-2: For Jazz, we delivered the Vision & Strategy session and had a call on item design. Right now, the decision is sitting with their leadership team on survey ',NULL,now()),
('Cognex|Cognex-Q3-2025','Cognex','Cognex-Q3-2025','PS support','US','In progress','Low','Heidi Muhle',4,'Paul Mastrangelo',55,'N/A',0,'2025-07-02','2026-09-01','2026-10-01','2026-09-01','2025-07-02','Survey 2026-09-01','2026-09-01','27-3-2026 agreed on a project flow: Work with stakeholders to define the Glint Survey Questions, Draft Communications - June/July (partner with Paul)/2.	Finalize Glint Survey Questions, Translations, and Communications – August (Cognex)/Launch Glint Survey and monitor participation September (Cognex)/Review results and determine next steps – September/October (partner with Paul for Insights review)',NULL,now()),
('Almirall|Almirall-360-Q1-Q2-2026','Almirall','Almirall-360-Q1-Q2-2026','CS and PS Support And 360','EU','In progress','Medium','Heidi Muhle',32,'Avneeta Solanki',36,'Ivan de las Cuevas Ruiz',11,NULL,NULL,NULL,'Mid June-26','2026-02-02','Delivery end 2026-06-15','2026-06-15',NULL,NULL,now()),
('PIMCO Prima Real Estate|Pimco Prime Real Estate-Engagement','PIMCO Prima Real Estate','Pimco Prime Real Estate-Engagement','CS Support','EU','Not started','Medium','Ivan De Las Cuevas Ruiz',40,'N/A',0,'N/A',0,NULL,NULL,NULL,'2026-09-30','2026-03-11','Delivery end 2026-09-30','2026-09-30','4-2 I gave Ivan all the details, he will make the appointment with Annette for the KO meeting. 6-2-2026 Ivan has a PIMCO 360 Project Kick Off Call on the 11th March at 11:00 AM CET. 10-2-2026 Ivan sent a message to Annette again about his login. 24-2-2026 Ivan won''t be given access to the IT system by them. So he can only watch and not even do anything. He''s been allocated 40 hours for the Standard Survey Configuration, 37 hours for a 360-degree configuration, and a 25-hour bucket for technical questions, etc. According to Heidi, the allocated hours in this model are generally used. In fact, s',NULL,now()),
('PIMCO Prima Real Estate|Pimco Prime Real Estate-Bucket of Hours (25)','PIMCO Prima Real Estate','Pimco Prime Real Estate-Bucket of Hours (25)','CS Support','EU','In progress','Low','Ivan De Las Cuevas Ruiz',25,'N/A',0,'N/A',0,NULL,NULL,NULL,'2026-12-31','2026-02-01','Delivery end 2026-12-31','2026-12-31','4-2 I gave Ivan all the details, he will make the appointment with Annette for the KO meeting',NULL,now()),
('SoFi|SoFi Bank-2026','SoFi','SoFi Bank-2026','CS Support','US','In progress','Low','Stephanie Novack',60,'N/A',0,'N/A',0,NULL,NULL,NULL,'2026-12-31','2026-02-01','Delivery end 2026-12-31','2026-12-31','5-2 I handed over the project to Steph on February 5th and asked her to let me know when the KO meeting was. 9-2-2026 11 Feb. KO meeting.',NULL,now()),
('Douglas|Douglas-CS-Q1-Q2-2026','Douglas','Douglas-CS-Q1-Q2-2026','CS Support / Bucket of hours','EU','In progress','Low','Heidi Muhle',55,'N/A',0,'N/A',0,'2026-03-11',NULL,NULL,'End of June','March-26',NULL,NULL,'3-3-2026 Next steps: 1.Kick-off with local HR/2.Viva Glint technical readiness (target: end of March)/3.Employee data & kiosk logins/4.Team Conversation Template',NULL,now()),
('Warburtons|Warburtons – Q2 2026','Warburtons','Warburtons – Q2 2026','PS support / Insight review/Vision & Strategy session','UK','In progress',NULL,'Heidi Muhle',1,'Kirsty Thompson - Clarke',42,'N/A',0,NULL,'2026-05-19','2026-06-01','2026-06-01','2026-04-01','Survey 2026-05-19','2026-05-19','4-3 Warburtons Survey goes live I believe from 28th April for 3 weeks so I estimate it would close on or around 19th May. They would like their Results presentation on 26th May. It is quite tight, usually the preview would be 5 working days post survey and the final presentation to senior leadership would be 24-36 hours post that to allow for any updates',NULL,now()),
('Syngenta|Syngenta – Q2 2026','Syngenta','Syngenta – Q2 2026','CS and PS Support','Switserland','In progress',NULL,'Ivan De Las Cuevas Ruiz',55,'Kirsty Thompson - Clarke',39,'Avneeta Solanki',16,'2026-05-05','3rd June to 24th June','w/c 13 July or w/c20 July','2026-07-30','2026-04-01','Delivery end 2026-07-30','2026-07-30','Mail JK: This customer has not confirmed a kick off date but as their next engagement launch is scheduled for June 2026 I anticipate that you should be able to start working with them in April 2026 at the latest (subject to contracts being signed in time!). They have also purchased a ‘bucket of hours’ so they may want to start utilising those hours with you with regular check ins as they are keen on platform optimisation and learning about new features and functionalities. Mail Kirsty: Yarmilla do let me know if I can support in anyway to get this over the line. I am out of the country W/C 29t',NULL,now()),
('Trane Technologies|Trane-Q2-Q3-2026','Trane Technologies','Trane-Q2-Q3-2026','CS Support / Survey QA/Bucket of hours','US','Not started',NULL,'Heidi Muhle',55,'N/A',0,'N/A',0,'2026-05-18',NULL,NULL,'Oct-2026','2026-08-01','Delivery end 2026-10-15','2026-10-15',NULL,NULL,now()),
('BioMarin|BioMarin-2026','BioMarin','BioMarin-2026','CS and PS Support','US','Not started',NULL,'Heidi Muhle',67,'Paul Mastrangelo',65,'N/A',0,'First week of June',NULL,NULL,NULL,'May-2026',NULL,NULL,'17-4 Thank you for checking in.  We are launching our spring survey next Monday which lasts 2 weeks.  It would be great if things will be finalized within the next 2 weeks and you could help with analyzing the data.
Then we can review, strategize, design, and plan for the October survey (we do 2 surveys per year) and other surveys.',NULL,now()),
('North Mississippi Health Services|','North Mississippi Health Services',NULL,NULL,'US',NULL,NULL,'Heidi Muhle/Angie',73,'Paul Mastrangelo',40,NULL,NULL,NULL,'27-8-2026-13-9-2026',NULL,NULL,'May-2026',NULL,NULL,'Mail Kim to Desiree:Hi Desiree, we can definitely connect whenever you’d like. Aside from the technical bumps we’ve experienced with our firewall blocking your emails to us, we’re in the middle of a Workday implementation and I’ve fallen a bit behind in getting things back to our Legal. That said, our Legal is also swamped and both the MSA and SOW are still with them. Our goal is still to get everything signed off no later than May 1. 1-5-2026 our survey is scheduled to go live on August 27 and close on September 13.',NULL,now()),
('BMC Software|','BMC Software',NULL,NULL,'US',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,now()),
('Breitling|Breitling-Q1-Q2-2025|old','Breitling','Breitling-Q1-Q2-2025','CS Support','Switzerland','Completed','Low','Ezra Fermanis',62,'Kirsty Thompson - Clarke',5,'Heidi Muhle',8,NULL,NULL,NULL,'2026-03-31','2025-04-07','Delivery end 2026-03-31','2026-03-31','Ezra provides monthly check ins-28-1-2026 Ezra has missed a few appointments, did he call Breitling on January 26? 24-2-2026 Breitling. Heidi, you and Ezra had a handover last week. For the next contract, as you''ve heard, they''d like a CS person in Europe. Initially, following that conversation, Ezra indicated he could still work from New Zealand within certain time slots. I informed Breitling about this mid-last week, also with an eye to the new contract, and they were very happy about it. At the end of last week, Ezra reconsidered, however, because it wouldn''t fit into his family life. I''ve ',NULL,now()),
('Dentsu|Densu-Q1-2026|old','Dentsu','Densu-Q1-2026','PS support','UK','Completed','Low','Ezra Fermanis',3,'Avneeta Solanki',40,'N/A',0,NULL,NULL,NULL,'2026-02-01','2026-01-01','Delivery end 2026-02-01','2026-02-01','1 x Insight Review due to be delivered in Q1 of 2026. Requires 1 x nsight Review in Japanese. Ipsos to provide costs for Japanese consultant to support. Proposal for our time and Ipsos consultant to be submitted to Dentsu. 12-2-2026 Avneeta is busy completing the Final Presentation, she also indicated this: I won''t be presenting another version (they will do this internally) so I need to send over the revised version next week and will offer a call to go through the new content if they wish. I think that will be it for Dentsu for now.',NULL,now()),
('European Training Foundation (ETF)|ETF-CS-Q4-25-Q1-26|old','European Training Foundation (ETF)','ETF-CS-Q4-25-Q1-26','CS Support','EU','Completed','Medium','Ivan De Las Cuevas Ruiz',61,'N/A',0,'N/A',0,NULL,NULL,NULL,'2026-03-31','2026-01-01','Delivery end 2026-03-31','2026-03-31','Platform Implementation and 1 x survey configuration. Ivan on holiday 9th Jan - 27th Jan in Japan, but customer has been given guidance on what to do while he is away so they can reconvene end of Jan to finalize prep for launch in mid February 13-2-2026 Survey start 16-2 for 3 weeks. Ivan gives a Training for thier leaders on the 23rd of March at 4:30 PM. 2-3 So, we extended the survey by a week. It closes next Monday.. I have to help them release results and have two more calls. I also have a few hours left with them and we discussed having one or more session with them to go over prepping fo',NULL,now()),
('Maire|Maire-2026|old','Maire','Maire-2026','CS and PS Support','EU','Completed','Medium','Ivan De Las Cuevas Ruiz',27,'Avneeta Solanki',6.5,'Heidi Muhle',6,'2026-05-11','N/A','N/A','2026-05-29','2026-01-01','Delivery end 2026-05-29','2026-05-29','KO date = 29-1-2026. Also Avneeta and Kate need some guidance on how to shape the team converstions session. First, just Ivan''s work. Then the other things need to be activated at Maire''s. JK had already passed on the hours to Pablo. Depending on when the surveys start, we''ll see if Pablo can still do this. 27-1-2026 input Survey:Starts Nov 12 - Ends Dec 14. 5-2 Hi Ivan, how are you today? I had a quick question about Maire''s status. Have you been able to work with Heidi on a solution for their bad data? Do you have any insight into when your CS work needs to be completed? Should I send Luka a',NULL,now()),
('Sage|Sage-Q3-2025|old','Sage','Sage-Q3-2025','CS and PS Support','UK','Completed','Medium','Ivan De Las Cuevas Ruiz',3,'Kirsty Thompson - Clarke',130,'N/A',0,NULL,NULL,NULL,'2026-12-31','2025-07-23','Delivery end 2026-12-31','2026-12-31','There are still 64 hours of Kirsty''s budget to be used, just check with her',NULL,now()),
('PIMCO Prima Real Estate|Pimco Prime Real Estate-360 Configuration|old','PIMCO Prima Real Estate','Pimco Prime Real Estate-360 Configuration','CS Support','EU','Completed','Low','Ivan De Las Cuevas Ruiz',37,'N/A',0,'Heidi Muhle',6,NULL,NULL,NULL,'2026-09-01','2026-02-01','Delivery end 2026-09-01','2026-09-01','4-2 I gave Ivan all the details, he will make the appointment with Annette for the KO meeting. Also informed Heidi about the support hours',NULL,now()),
('Serco|Serco-Enablement_May2025|old','Serco','Serco-Enablement_May2025','CS and PS Support','UK','Completed','Low','Ezra Fermanis',11,'Paul Mastrangelo',40,'Angela Schwingel',21,NULL,NULL,NULL,'Update requested from Paul','2025-05-29',NULL,NULL,'Insight Review (January 2026) and HRBP Training. November survey closed successsfully, CS time used up but now on Time & Materials contract 8hrs for continuing CS support. Paul to deliver 2 x Insight Reviews and HRBP Training sessions with Angie supporting 28-1-2026 mail Paul: Hi Yarmilla. I have training sessions until 18 February. I delivered the HR Preview of results 2 weeks ago, but I have not heard about scheduling the Executive Review. I will ask them. I am also trying to set up a meeting to consider linking their survey results to objective signals. I think all of these things should be',NULL,now()),
('Serco|SercoViewPoint_Sept2025|old','Serco','SercoViewPoint_Sept2025','CS and PS Support','UK','Completed','Low','Ezra Fermanis',40,'Paul Mastrangelo',65,'Angela Schwingel',10,NULL,NULL,NULL,'2026-06-03','2025-05-21','Delivery end 2026-06-03','2026-06-03',NULL,NULL,now()),
('Draper|Draper-Q3-2025|old','Draper','Draper-Q3-2025','PS support','US','Completed','Medium','Angela Schwingel',2,'Paul Mastrangelo',34,'N/A',0,NULL,NULL,NULL,'2026-06-03','2025-08-01','Delivery end 2026-06-03','2026-06-03','I x Insight Review has been delayed since the summer. Paul about to do final presentation after CHRO asked for some minor amendments. Paul awaiting for access to granted again to the platform so he can complete further updates. This should not roll over beyond end of January. They have asked for a lot which Paul has provided but they have strict instructions from me that any further support / changes will incur costs which they accept. 3-3 Paul still doesn''t have access. I sent an email to Vin today from my position.',NULL,now()),
('IMC|IMC Trading-Q1-Q2-2026|old','IMC','IMC Trading-Q1-Q2-2026','CS and PS Support / Insight review/','EU','Completed',NULL,'Ivan De Las Cuevas Ruiz',38,'Kirsty Thompson - Clarke',40,'N/A',0,'2026-03-12',NULL,NULL,'2026-05-05','2026-04-01','Delivery end 2026-05-05','2026-05-05',NULL,NULL,now());
-- 1) exact normalised-name match
update glint_delivery g set company_id=c.id from companies c where g.company_id is null and lower(regexp_replace(g.client_name,'[^a-z0-9]','','g'))=lower(regexp_replace(c.name,'[^a-z0-9]','','g'));
-- 2) partial match (client name is a prefix/substring of the CRM account name or vice versa)
update glint_delivery g set company_id=c.id from companies c where g.company_id is null and (
  lower(regexp_replace(c.name,'[^a-z0-9]','','g')) like lower(regexp_replace(g.client_name,'[^a-z0-9]','','g'))||'%'
  or lower(regexp_replace(g.client_name,'[^a-z0-9]','','g')) like lower(regexp_replace(c.name,'[^a-z0-9]','','g'))||'%'
);
-- 3) explicit aliases for names that differ on the sheet vs the CRM
update glint_delivery g set company_id = m.cid from (
  select 'PIMCO Prima Real Estate'::text as cn, (select id from companies where name='PIMCO Prime Real Estate' limit 1) as cid
  union all select 'Breitling', (select id from companies where name ilike 'breitling' limit 1)
) m where g.client_name = m.cn and g.company_id is null;